# Introducción

NumPy es un paquete de Python para realizar computación cientifíca. Entre las funcionalidades de NumPy se encuentra operaciones matriciales las cuales son usadas en redes neuronales. Una de las ventajas de usar NumPy es que las operaciones matriciales estan optimizadas con lenguaje C. A continuación daremos ejemplos del uso de operaciones matriciales con NumPy.

# Importando NumPy

La forma estandard de importar NumPy es la siguiente:

In [0]:
import numpy as np 

**Ejercicio**: vamos a acceder a la versión de numpy ejecutando lo siguiente en la siguiente celda y ejecutando enter: 

print(np.\_\_version\_\_)

# Tipos de Datos en NumPy 

NumPy tiene el objeto ndarray los cuales son similares a la listas de Python, sin embargo, pueden tener diferentes números de dimensiones. Entre los tipos de datos que tiene NumPy están: escalares, vectores y matrices. 

## Escalares 

Escalares son tipos de datos que tienen dimensión cero, uno puede pensar en ellos como entes atomicos (no se pueden dividir). En la siguiente celda declaramos un valor entero x y luego mostramos su atributo shape (dimensión).  

In [46]:
x = np.array(5)
print(x.shape)

()


## Vectores 

Los vectores tienen dimensión 1 y deben contener elementos del mismo tipo, por ejemplo puedo crear un vector con valores de tipo int o float pero no de ambos tipos. En la siguiente celda creamos un vector a partir de una lista que contiene enteros y luego desplegamos su atributo shape.

In [47]:
x2 = np.array([1, 2, 3, 4, 5])
print(x2.shape)

(5,)


Podemos acceder a elementos individuales dentro del ndarray de la siguiente manera:

In [51]:
x2[2] # accesamos al segundo elemento de x2 

3

Tambien podemos usar técnicas de indexamiento, por ejemplo si quisieramos acceder del segundo elemento al cuarto de x2 ejecutariamos lo siguiente:

In [52]:
x2[1:4]

array([2, 3, 4])

En cambio si quisieramos acceder del tercer elemento hasta el final ejecutariamos lo siguiente: 

In [53]:
x2[2:]

array([3, 4, 5])

## Matrices

Las matrices son estructuras de datos en NumPy que tienen dos dimensiones (filas y columnas), para crear una matriz en NumPy debes de pasar una lista de listas de la siguiente manera. 

In [0]:
x3 = np.array([[1, 2, 3], [4, 5, 6]])

In [59]:
print(x3) # mostrando la información de x3

[[1 2 3]
 [4 5 6]]


In [60]:
print(x3.shape) # mostrando la dimensión de x3 

(2, 3)


Podemos acceder a elementos individuales o a submatrices de la siguiente forma:

In [61]:
print(x3[0,0]) # Elemento en la primera fila y primera columna

1


In [62]:
print(x3[0:,0]) # Primera columna 

[1 4]


# Cambiando las dimensiones de un NumPy array

Por ejemplo definamos el siguiente vector. 

In [63]:
x4 = np.array([7, 8 , 9 , 10])
print(x4.shape)

(4,)


Supongamos que necesitamos que este vector sea una matriz 1x4 el código sera el siguiente: 

In [64]:
temp1 = x4.reshape(1, 4)
print(temp1)
print(temp1.shape)

[[ 7  8  9 10]]
(1, 4)


De igual manera podemos crear una matriz de 4x1 a partir del vector x4 de la siguiente manera: 

In [65]:
temp2 = x4.reshape(4, 1)
print(temp2)
print(temp2.shape)

[[ 7]
 [ 8]
 [ 9]
 [10]]
(4, 1)


Tambien se puede usar la siguiente instrucción:

In [66]:
temp1 = x4[None, :]
print(temp1)
print(temp1.shape)

[[ 7  8  9 10]]
(1, 4)


In [67]:
temp2 = x4[:, None]
print(temp2)
print(temp2.shape)

[[ 7]
 [ 8]
 [ 9]
 [10]]
(4, 1)


**Ejercicio**: Crear un vector con los siguientes elementos 2, 3, 5, 7 y luego a partir de ese vector crear una matriz con dimensiones 4 filas y 1 columna. 

# Operaciones entre una matriz y un escalar

Una ventaja de usar NumPy array sobre las listas de Python es que podemos realizar operaciones sobre cada elemento sin la obligación de usar bucles. Por ejemplo podemos sumar un escalar a cada elemento de una matriz de la siguiente manera: 

In [68]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [70]:
A + 5  # Sumo 5 a cada elemento de la matriz A 

array([[6, 7],
       [8, 9]])

Otra operación común es multiplicar un escalar por una matriz, por ejemplo  para multiplicar la matriz A definida anteriormente por el escalar $\frac{1}{10}$ debemos ejecutar el siguiente código: 

In [71]:
A * (1/10)

array([[0.1, 0.2],
       [0.3, 0.4]])

De igual manera podemos usar las operaciones - (resta) y / (división) con escalares.

**Ejercicio**: Definir la siguiente matriz:  

$\left[ \begin{array}{cc}
4 & 7  \\
9 & 2  \\
\end{array} \right]$

Y restarle -3 a cada uno de sus elementos. 

# Operaciones de matrices 

La suma de matrices se define de manera natural sumando cada uno de los elementos de las matrices, para realizar esta operación las matrices deben tener el mismo número de filas y columnas. A continuación definiremos la matriz B con las mismas dimensiones de la matriz A y realizaremos la suma entre ambas matrices. 

In [72]:
B = np.array([[3, 5], [14, 4]])
print(B)

[[ 3  5]
 [14  4]]


In [73]:
print(A) # Mostramos la matriz A 

[[1 2]
 [3 4]]


In [74]:
A + B # Sumamos A y B 

array([[ 4,  7],
       [17,  8]])

De igual manera podemos realizar la operación de multiplicar cada uno de los elementos de las matrices A y B utilizando el operador *. No hay que confundir esta operación con la multiplicación matricial la cual definiremos posteriormente. 

In [75]:
A * B 

array([[ 3, 10],
       [42, 16]])

Otra forma en la que podemos realizar la anterior operación es con la función multiply de NumPy de la siguiente forma: 

In [76]:
np.multiply(A, B )

array([[ 3, 10],
       [42, 16]])

Tambien es posible realizar las operaciones - (resta) y / (división). 

**Ejercicio**: Hacer la resta de las siguientes matrices: 


$$
  \left[ \begin{array}{cc}
1 & 0 \\
0 & 1
\end{array} \right] - \left[ \begin{array}{cc}
1 & 0 \\
0 & 1
\end{array} \right] $$

$$
  \left( \begin{array}{cc}
1 & 0 \\
0 & 1
\end{array} \right) \times \left( \begin{array}{cc}
1 & 0 \\
0 & 1
\end{array} \right) =\left( \begin{array}{cc}
1 & 0 \\
0 & 1
\end{array} \right)$$

# Matriz Producto

La matriz producto A y B es una operación que produce una matriz con número de filas iguales a las de A y número de columnas iguales a las de B. Para que esta operación pueda darse es necesario que el número de columnas de la matriz A sea igual al número de filas de B. A continuación vamos a ejemplificar esta operación.


In [78]:
M = np.array([[1, 2, 3], [4, 5, 6]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [79]:
N = np.array([[7, 8], [9, 10], [11, 12]])
print(N)
print(N.shape)

[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


Para calcular la matriz producto usaremos la función matmul del paquete NumPy.

In [80]:
np.matmul(M, N)

array([[ 58,  64],
       [139, 154]])

El elemento que esta en la primera fila y primera columna se calcula como la suma de los elementos del  producto entre la primera fila de M con la primera columna de N, de igual manera el elemento que ocupa la primera fila y segunda columna se ha obtenido de la suma de los elementos del producto entre la primera fila de M con la segunda columna de N, y así sucesivamente. 

**Ejercicio**: Calcular el producto de las siguientes matrices: 

$$
  \left( \begin{array}{cc}
1 & 0 \\
0 & 1
\end{array} \right) \times \left( \begin{array}{cc}
1 & 0 \\
0 & 1
\end{array} \right) $$

# Transpuesta de una matriz



La matriz transpuesta tiene los mismos valores que la matriz original, sin embargo, las filas y columnas se intercambian. En NumPy podemos calcular la matriz transpuesta utilizando el atributo T o utilizando la función transpose de NumPy. A continuación vamos a dar un ejemplo. 

In [81]:
Z = np.array([[2, 3, 4], [1, -5, 9]])
print(Z)
print(Z.shape)

[[ 2  3  4]
 [ 1 -5  9]]
(2, 3)


In [82]:
print(Z.T)
print(Z.T.shape)

[[ 2  1]
 [ 3 -5]
 [ 4  9]]
(3, 2)


In [83]:
print(np.transpose(Z))
print(np.transpose(Z).shape)

[[ 2  1]
 [ 3 -5]
 [ 4  9]]
(3, 2)


**Ejercicio**: Calcula la transpuesta de la siguiente matriz.

$\left[ \begin{array}{ccc}
1 & 7 &  3\\
7 & 4 & -5 \\
3 & -5 & 6
\end{array} \right]$
